-- Baseline: the schema as Hibernate's ddl-auto=update had created it (taken from pg_dump), so
-- fresh databases match existing ones, constraint names included. Existing databases are
-- marked as already at V1 (spring.flyway.baseline-on-migrate) and never run this file.
-- From here on, every schema change is a new V<n>__description.sql; never edit an applied one.

CREATE TABLE orders (
    id           bigint GENERATED BY DEFAULT AS IDENTITY,
    created_at   timestamp(6),
    order_id     varchar(255),
    payment_id   bigint,
    status       varchar(255),
    total_amount double precision NOT NULL,
    user_id      bigint,
    CONSTRAINT orders_pkey PRIMARY KEY (id),
    CONSTRAINT uk_orders_order_id UNIQUE (order_id)
);
CREATE INDEX idx_orders_user_id ON orders (user_id);

CREATE TABLE order_items (
    id         bigint GENERATED BY DEFAULT AS IDENTITY,
    price      double precision NOT NULL,
    product_id bigint,
    quantity   integer          NOT NULL,
    order_id   bigint,
    CONSTRAINT order_items_pkey PRIMARY KEY (id),
    CONSTRAINT fkbioxgbv59vetrxe0ejfubep1w FOREIGN KEY (order_id) REFERENCES orders (id)
);

-- Transactional outbox for order.paid events (see OutboxPublisher)
CREATE TABLE outbox_events (
    id           bigint GENERATED BY DEFAULT AS IDENTITY,
    created_at   timestamp(6),
    event_id     varchar(255) NOT NULL,
    payload      text         NOT NULL,
    published_at timestamp(6),
    routing_key  varchar(255) NOT NULL,
    CONSTRAINT outbox_events_pkey PRIMARY KEY (id),
    CONSTRAINT uk7ba1uqwbn85u1g6jg4ja1tk6k UNIQUE (event_id)
);
