server:
  port: 8086

jwt:
  secret: ${JWT_SECRET:change-this-shared-secret-change-this-shared-secret}

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

razorpay:
  key: ${RAZORPAY_KEY:razorpay-key-not-set}
  secret: ${RAZORPAY_SECRET:razorpay-secret-not-set}
spring:
  application:
    name: payment-service
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
  datasource:
#    url: jdbc:mysql://localhost:3306/paymentdb
    url: jdbc:mysql://payment-db:3306/paymentdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect