-- Baseline: the schema as Hibernate's ddl-auto=update had created it (taken from pg_dump), so
-- fresh databases match existing ones, constraint names included. Existing databases are
-- marked as already at V1 (spring.flyway.baseline-on-migrate) and never run this file.
-- From here on, every schema change is a new V<n>__description.sql; never edit an applied one.

CREATE TABLE payments (
    id           bigint GENERATED BY DEFAULT AS IDENTITY,
    order_id_ref varchar(255),
    payment_date timestamp(6),
    payment_id   varchar(255),
    signature    varchar(255),
    status       varchar(255),
    user_id      bigint,
    CONSTRAINT payments_pkey PRIMARY KEY (id),
    CONSTRAINT ukt4ffsaqe8d6i83gs100u2y3l1 UNIQUE (payment_id)
);

-- Transactional outbox for payment events (see OutboxPublisher)
CREATE TABLE outbox_events (
    id           bigint GENERATED BY DEFAULT AS IDENTITY,
    created_at   timestamp(6),
    event_id     varchar(255) NOT NULL,
    payload      text         NOT NULL,
    published_at timestamp(6),
    routing_key  varchar(255) NOT NULL,
    CONSTRAINT outbox_events_pkey PRIMARY KEY (id),
    CONSTRAINT uk7ba1uqwbn85u1g6jg4ja1tk6k UNIQUE (event_id)
);
