-- Every Razorpay order this service creates. Lets PaymentReconciler find payments that were
-- made but never verified (browser closed after paying, Razorpay unreachable during
-- verification) by asking Razorpay directly. OPEN until a payment is recorded (PAID) or the
-- attempt is given up on (ABANDONED).
CREATE TABLE payment_attempts (
    id                bigint GENERATED BY DEFAULT AS IDENTITY,
    razorpay_order_id varchar(255) NOT NULL,
    order_id_ref      varchar(255) NOT NULL,
    user_id           bigint,
    amount_paise      bigint       NOT NULL,
    status            varchar(20)  NOT NULL,
    created_at        timestamp(6) NOT NULL,
    updated_at        timestamp(6) NOT NULL,
    CONSTRAINT payment_attempts_pkey PRIMARY KEY (id),
    CONSTRAINT uk_payment_attempts_razorpay_order_id UNIQUE (razorpay_order_id),
    CONSTRAINT payment_attempts_status_valid CHECK (status IN ('OPEN', 'PAID', 'ABANDONED'))
);
CREATE INDEX idx_payment_attempts_status_created_at ON payment_attempts (status, created_at);
