-- Baseline: the schema as Hibernate's ddl-auto=update had created it (taken from pg_dump), so
-- fresh databases match existing ones, constraint names included. Existing databases are
-- marked as already at V1 (spring.flyway.baseline-on-migrate) and never run this file.
-- From here on, every schema change is a new V<n>__description.sql; never edit an applied one.

CREATE TABLE users (
    id          bigint GENERATED BY DEFAULT AS IDENTITY,
    cart_id     integer      NOT NULL,
    email       varchar(255) NOT NULL,
    name        varchar(255),
    order_ids   bigint[],
    password    varchar(255) NOT NULL,
    product_ids bigint[],
    role        varchar(255) NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email)
);
