server:
  port: 8085

jwt:
  secret: ${JWT_SECRET:change-this-shared-secret-change-this-shared-secret}

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

spring:
  application:
    name: order-service
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
  datasource:
    #    url: jdbc:mysql://localhost:3306/orderdb
    url: jdbc:mysql://order-db:3306/orderdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
