-- Baseline: the schema as Hibernate's ddl-auto=update had created it (taken from pg_dump), so
-- fresh databases match existing ones, constraint names included. Existing databases are
-- marked as already at V1 (spring.flyway.baseline-on-migrate) and never run this file.
-- From here on, every schema change is a new V<n>__description.sql; never edit an applied one.

CREATE TABLE products (
    id          bigint GENERATED BY DEFAULT AS IDENTITY,
    active      boolean          NOT NULL,
    brand       varchar(255),
    category    varchar(255),
    color       varchar(255),
    description varchar(255),
    discount    integer          NOT NULL,
    image       varchar(255),
    model       varchar(255),
    price       double precision NOT NULL,
    stock       integer          NOT NULL,
    title       varchar(255)     NOT NULL,
    user_id     integer          NOT NULL,
    CONSTRAINT products_pkey PRIMARY KEY (id)
);

-- order.paid events already applied (consumer deduplication)
CREATE TABLE processed_events (
    event_id     varchar(255) NOT NULL,
    processed_at timestamp(6),
    CONSTRAINT processed_events_pkey PRIMARY KEY (event_id)
);
