-- Stock is taken when an order is placed and held here until the order is paid (CONFIRMED)
-- or expires (RELEASED, stock returned). One row per order line.
CREATE TABLE stock_reservations (
    id         bigint GENERATED BY DEFAULT AS IDENTITY,
    order_id   varchar(255) NOT NULL,
    product_id bigint       NOT NULL,
    quantity   integer      NOT NULL,
    status     varchar(20)  NOT NULL,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6) NOT NULL,
    CONSTRAINT stock_reservations_pkey PRIMARY KEY (id),
    CONSTRAINT stock_reservations_quantity_positive CHECK (quantity > 0),
    CONSTRAINT stock_reservations_status_valid CHECK (status IN ('RESERVED', 'CONFIRMED', 'RELEASED'))
);
CREATE INDEX idx_stock_reservations_order_id ON stock_reservations (order_id);
