-- Baseline: the schema as Hibernate's ddl-auto=update had created it (taken from pg_dump), so
-- fresh databases match existing ones, constraint names included. Existing databases are
-- marked as already at V1 (spring.flyway.baseline-on-migrate) and never run this file.
-- From here on, every schema change is a new V<n>__description.sql; never edit an applied one.

CREATE TABLE carts (
    id          bigint GENERATED BY DEFAULT AS IDENTITY,
    total_price double precision NOT NULL,
    user_id     bigint,
    CONSTRAINT carts_pkey PRIMARY KEY (id)
);

CREATE TABLE cart_items (
    id         bigint GENERATED BY DEFAULT AS IDENTITY,
    price      double precision NOT NULL,
    product_id bigint,
    quantity   integer          NOT NULL,
    cart_id    bigint,
    CONSTRAINT cart_items_pkey PRIMARY KEY (id),
    CONSTRAINT fkpcttvuq4mxppo8sxggjtn5i2c FOREIGN KEY (cart_id) REFERENCES carts (id)
);

-- order.paid events already applied (consumer deduplication)
CREATE TABLE processed_events (
    event_id     varchar(255) NOT NULL,
    processed_at timestamp(6),
    CONSTRAINT processed_events_pkey PRIMARY KEY (event_id)
);
